------------- Script by Inj3, PROHIBITED to copy the code !
------------- If you have any language to add or suggestion, contact me on my steam.
------------- If you want to take a piece of code -> contact Inj3
------------- GNU General Public License v3.0
------------- https://steamcommunity.com/id/Inj3/
------------- www.centralcityrp.fr/ --- Affiliated Website 
------------- https://steamcommunity.com/groups/CentralCityRoleplay --- Affiliated Group
if SERVER then return end

CentralTable = {}

CentralTable.LangImprovedFpsBooster = {
["FR"] = {
Central_Texte1 = "Quitter",
Central_Texte2 = "Vous n'avez cochée aucune case dans l'onglet Options Optimisation, Improved Fps Booster ne peut démarrer.",
Central_Texte3 = "FPS détection",
Central_Texte4 = "Attention, ce convar 'Shadow Removed' désactive aussi la lumière de votre lampe de poche.",
Central_Texte5 = "Actuel :",
Central_Texte6 = "Activer",
Central_Texte7 = "Désactiver",
Central_Texte9 = "Si vous rencontrez des problèmes graphiques ou crashs, utilisez le button Options pour modifier vos paramètres. Pour ouvrir Improved FPS Booster /boost.",
Central_Texte10 = "Pour ouvrir Improved FPS Booster /boost.",
Central_Texte11 = "Vous avez réinitialisé vos paramètres par défaut, pour ouvrir Improved FPS Booster /boost.",
Central_Texte12 = "Voulez-vous activer Improved FPS Booster ?",
Central_Texte13 = "Pour remplacer les paramètres par défaut, activer Improved Fps Booster",
Central_Texte14 = "OFF (Désactivé)",
Central_Texte15 = "Optimisation",
Central_Texte16 = "Activer la performance multi-coeur de votre CPU (Peut être instable)",
Central_Texte17 = "Rendu multi-coeur",
Central_Texte18 = "Supprimer SkyBox",
Central_Texte19 = "Supprimer l'arrière plan",
Central_Texte20 = "Supprimer Spray",
Central_Texte21 = "Retire l'effet spray",
Central_Texte22 = "Supprimer Dents",
Central_Texte23 = "Les dents sont retirées sur les models",
Central_Texte24 = "Retirer effet M9k",
Central_Texte25 = "Retirer les particules sur les armes M9K",
Central_Texte26 = "Ombre - Lampe",
Central_Texte27 = "Enlève les ombres sur les entités, et enlève la lumière de votre lampe de poche",
Central_Texte28 = "Autre commande désactivé",
Central_Texte29 = "Activation automatique [FPS Booster]",
Central_Texte30 = "Si Improved Fps Booster est désactivé, cette case à cocher sera utilisée pour le démarrer automatiquement après avoir quitté",
Central_Texte31 = "Afficher FPS sur votre HUD",
Central_Texte32 = "Afficher vos FPS sur votre HUD, vous pouvez ajuster la position avec les sliders ci-dessous",
Central_Texte33 = "Position (gauche-droite) :",
Central_Texte34 = "Position (haut-bas) :",
Central_Texte35 = "Fermer & charger",
Central_Texte36 = "Cocher/Décocher tout",
Central_Texte37 = "Paramètres des options Chargée",
Central_Texte38 = "Langue",
Central_Texte39 = "dans la map",
Central_Texte40 = "Filtre Texture (lissage)",
Central_Texte41 = "Filtre Lumière (lissage)",
Central_Texte42 = "Retire le lissage sur les textures",
Central_Texte43 = "Retire le lissage sur la lumière",
},
["EN"] = {
Central_Texte1 = "Close",
Central_Texte2 = "You have not checked any checkbox in the Options Tab Optimization, Improved Fps Booster cannot load, it disabled automatically.",
Central_Texte3 = "FPS detection",
Central_Texte4 = "Be careful this convar 'Shadow Removed' also deactivates the light of your flashlight.",
Central_Texte5 = "Current :",
Central_Texte6 = "Enable",
Central_Texte7 = "Disable",
Central_Texte9 = "If you encounter graphic problems or crashes, use the Options button to change your settings. For open Improved Fps Booster /boost.",
Central_Texte10 = "For open Improved FPS Booster /boost.",
Central_Texte11 = "You have reset your settings to the default values.",
Central_Texte12 = "Do you want activate Improved FPS Booster ?",
Central_Texte13 = "To override the default settings, enable Improved Fps Booster",
Central_Texte14 = "OFF (Disabled)",
Central_Texte15 = "Optimization",
Central_Texte16 = "Take advantage of a Multi Core CPU",
Central_Texte17 = "Multicore Rendering",
Central_Texte18 = "Skybox Removed",
Central_Texte19 = "Remove skybox",
Central_Texte20 = "Spray Removed",
Central_Texte21 = "Remove the spray",
Central_Texte22 = "Teeth Removed",
Central_Texte23 = "Remove teeth on model",
Central_Texte24 = "M9K Effect Removed" ,
Central_Texte25 = "Remove particle effect on M9K",
Central_Texte26 = "Shadow - Lamp",
Central_Texte27 = "Removes shadows on entities, and removes light from your flashlight",
Central_Texte28 = "Other Command Disable",
Central_Texte29 = "Auto-enable after Close & Reload",
Central_Texte30 =  "If Improved Fps Booster is Off Disabled, this checkbox will be used to start it automatically after had Closed & Reload",
Central_Texte31 = "Show Framerate on HUD",
Central_Texte32 = "Display your FPS on your HUD, you can adjust the position with the sliders below",
Central_Texte33 = "Left-Right position :",
Central_Texte34 = "Up-Down position :",
Central_Texte35 = "Close & Reload",
Central_Texte36 = "Check All/Uncheck All",
Central_Texte37 = "Options settings Loaded",
Central_Texte38 = "Language",
Central_Texte39 = "on map",
Central_Texte40 = "Texture filter (smoothing)",
Central_Texte41 = "Light filter (smoothing)",
Central_Texte42 = "Removes smoothing on textures",
Central_Texte43 = "Removes smoothing on the light",
},
}	